### ISSUE TITLE
How to detect 1006 close code

### ISSUE THREAD

**Issue by dickensas** [square/SocketRocket#266] opened 2015-08-05 11:05 UTC
No callback is triggered when server closes the websocket connection with 1006

How to detect this?

**Comment by bithavoc** [comment] 2015-09-04 00:10
we're seeing this as well, I traced it back to `NSStreamEventErrorOccurred`.

turns out that when `NSStreamEventErrorOccurred` is triggered and `[aStream streamError]` is nil then it means the connection was abruptly interrupted, we should be calling `didCloseWithCode`.

Agree?

**Comment by bithavoc** [comment] 2015-09-04 00:14
I'll send a PR, will use `SRStatusCodeGoingAway` as closing status.

**Comment by dfed** [comment] 2015-10-03 00:04
I believe this is a duplicate of #260. Closing this out. If you disagree, please let me know and tell me why.

**Closed by dfed** 2015-10-03 00:04 UTC
