### ISSUE TITLE
Assertion failed: (aReadyState > _readyState)

### ISSUE THREAD

**Issue by nwalter08** [square/SocketRocket#75] opened 2013-02-01 23:43 UTC
Sometimes when I disconnect I get this error that craches my app.

Assertion failed: (aReadyState > _readyState), function -[SRWebSocket setReadyState:]

SRWebSocket.m, line 379

**Comment by hamin** [comment] 2015-01-01 00:36
@nwalter08 you still getting this crash?

**Comment by nwalter08** [comment] 2015-01-07 02:17
Hey @hamin! I haven't run that code in a looooong time :) Sorry I'm no help.

**Comment by kirik** [comment] 2015-02-12 17:03
Same here. I can't reproduce it manually, but sometimes it crashes my app..

**Comment by dfed** [comment] 2015-10-02 23:42
This looks like a duplicate of #54. Let me know if you disagree.

**Closed by dfed** 2015-10-02 23:42 UTC
